default_url_options:
  host: 'https://nemo2022.herokuapp.com'

names: 'nemo.brands.2022@gmail.com'
passwords: 'hrxlxhvlizoyrhgg'

AWS_ACCESS_KEY_ID: 'AKIA2XCTYBW43Z247AWU'
AWS_SECRET_ACCESS_KEY: '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'