default_url_options:
  host: 'https://nemo2022.herokuapp.com'

names: 'nemo.brands.2022@gmail.com'
passwords: 'hrxlxhvlizoyrhgg'

AWS_ACCESS_KEY_ID: 'AKIA2XCTYBW474WQDCRP'
AWS_SECRET_ACCESS_KEY: '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'