default_url_options:
  host: 'https://nemo2022.herokuapp.com'

names: 'nemo.brands.2022@gmail.com'
passwords: 'hrxlxhvlizoyrhgg'

AWS_ACCESS_KEY_ID: 'AKIA2XCTYBW46YL44IGL'
AWS_SECRET_ACCESS_KEY: '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'