default_url_options:
  host: 'https://nemo2022.herokuapp.com'

names: 'nemo.brands.2022@gmail.com'
passwords: 'hrxlxhvlizoyrhgg'

AWS_ACCESS_KEY_ID: 'AKIA2XCTYBW4Z6BGVFPO'
AWS_SECRET_ACCESS_KEY: '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'