default_url_options:
  host: 'https://nemo2022.herokuapp.com'

names: 'nemo.brands.2022@gmail.com'
passwords: 'hrxlxhvlizoyrhgg'

AWS_ACCESS_KEY_ID: 'AKIA2XCTYBW4XHECJFOI'
AWS_SECRET_ACCESS_KEY: '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'