default_url_options:
  host: 'https://nemo2022.herokuapp.com'

names: 'nemo.brands.2022@gmail.com'
passwords: 'hrxlxhvlizoyrhgg'

AWS_ACCESS_KEY_ID: 'AKIA2XCTYBW4SQ6GSVO7'
AWS_SECRET_ACCESS_KEY: '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'