default_url_options:
  host: 'https://nemo-brand.herokuapp.com/'

names: 'nemo.brands.2022@gmail.com'
passwords: 'hrxlxhvlizoyrhgg'

AWS_ACCESS_KEY_ID: 'AKIA2XCTYBW4ZBUUKZEC'
AWS_SECRET_ACCESS_KEY: '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'